# Generated by Django 3.1.7 on 2021-04-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_auto_20210411_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='name_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='name_kk',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='name_ru',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
