# Generated by Django 3.1.7 on 2021-04-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0013_auto_20210411_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='url',
            field=models.SlugField(blank=True, max_length=130, null=True, unique=True),
        ),
    ]
