# Generated by Django 3.1.7 on 2021-04-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0014_auto_20210411_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='video_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
