# Generated by Django 3.1.7 on 2021-04-17 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0015_auto_20210411_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, null=True, related_name='movies', to='movie.Genre', verbose_name='жанры'),
        ),
    ]
