# Generated by Django 3.1.4 on 2021-04-21 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0019_auto_20210421_0135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='url',
        ),
    ]
