# Generated by Django 3.1.7 on 2021-04-24 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0022_auto_20210421_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='subscription',
            field=models.BooleanField(default=False, verbose_name='По подписке'),
        ),
    ]
