# Generated by Django 3.1.4 on 2021-04-28 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0026_historyuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyuser',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
