# Generated by Django 3.1.4 on 2021-04-29 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0027_historyuser_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historyuser',
            options={'ordering': ['-date'], 'verbose_name': 'История пользователя', 'verbose_name_plural': 'Истории пользователей'},
        ),
    ]
