# Generated by Django 3.1.7 on 2021-05-09 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0029_profile_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyuser',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_users', to='movie.movie'),
        ),
        migrations.AlterField(
            model_name='historyuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_movies', to=settings.AUTH_USER_MODEL),
        ),
    ]
